version: '3'
services:
  bookkeeper:
    build: .
    image: towski0804/bookkeeper:latest
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mypostgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
  mypostgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - mypostgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123123
volumes:
  mypostgres: